const fs=require('fs');
const assert=(c,m)=>{if(!c)throw new Error(m)};
const setup=fs.readFileSync('github-setup.html','utf8');
const backend=fs.readFileSync('local-github-backend.js','utf8');
const integration=fs.readFileSync('assets/github-integration.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const installer=fs.readFileSync('INSTALL_ON_MY_COMPUTER.bat','utf8');
const launcher=fs.readFileSync('desktop-launcher.js','utf8');
assert(setup.includes('<h1 id="page-title">GitHub</h1>') && setup.includes('Connect GitHub'),'GitHub page must exist and explain account connection');
assert(setup.includes('Choose a repository'),'GitHub page must let the learner choose a repository');
assert(setup.includes('Add &amp; use repository'),'GitHub page must let the learner add a repository');
assert(setup.includes('csai-github-preferred-repo'),'GitHub page must persist the selected repository for publishing tools');
assert(index.includes('href="github-setup.html"'),'home page must link to GitHub');
assert(!backend.includes('DEFAULT_REPOSITORY'),'backend must require an explicit repository');
assert(backend.includes("Choose a GitHub repository first in GitHub"),'backend must reject publishing without repository selection');
assert(!integration.includes('DEFAULT_REPO'),'browser publishing must not have a hard-coded repository');
assert(integration.includes("SETUP_URL = '/github-setup.html'"),'publishing UI must link back to the GitHub page');
assert(!backend.includes('DEFAULT_REPOSITORY'),'backend must not contain a default repository constant');
assert(!integration.includes('DEFAULT_REPO'),'integration must not contain a default repository constant');
assert(!launcher.includes('TARGET_REPO'),'launcher must not contain a fixed repository target');
assert(!installer.includes('gh repo view '),'installer must not probe any fixed repository');
console.log('v5.57 main GitHub page contract PASS — connect account, explicitly choose/add repository, no inherited repository target.');
