'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'assets','studycore-export.js'),'utf8');
assert.match(source,/Export to StudyCore/);
assert.match(source,/one course at a time/i);
assert.match(source,/masteryLessons/);
assert.match(source,/masteryCommit/);
assert.match(source,/masteryTarget/);
assert.match(source,/Flashcards/);
const document={readyState:'loading',addEventListener(){},getElementById(){return null;}};
const sandbox={window:{location:{href:''}},document,URLSearchParams,Map,Set,fetch:async()=>{throw new Error('not used')},console};
vm.createContext(sandbox);
vm.runInContext(source,sandbox,{filename:'studycore-export.js'});
const api=sandbox.window.CSAIStudyCoreExport;
assert(api&&typeof api.buildStudyCoreUrl==='function');
const url=api.buildStudyCoreUrl('python',['py-loops','py-loops','py-lists'],'flashcards','a'.repeat(40),'5.76.0');
assert.match(url,/masteryCourse=python/);
assert.match(url,/masteryLessons=py-loops%2Cpy-lists/);
assert.match(url,/masteryTarget=flashcards/);
assert.match(url,/masteryCommit=/);
assert(!url.includes('py-loops%2Cpy-loops'),'duplicate lesson ids must be removed');
assert.throws(()=>api.buildStudyCoreUrl('python',[],'flashcards','a'.repeat(40),'5.76.0'),/at least one lesson/i);
assert.throws(()=>api.buildStudyCoreUrl('../python',['py-loops'],'flashcards','a'.repeat(40),'5.76.0'),/Choose a course/i);
console.log('StudyCore export contract PASS.');
