'use strict';
const fs=require('fs'), path=require('path'), assert=require('assert');
const root=path.resolve(__dirname,'..');
const courses=JSON.parse(fs.readFileSync(path.join(root,'assets','coursedata-source.json'),'utf8'));
const course=courses.find(c=>c.id==='software-engineering-practice');
assert(course,'Software Engineering in Practice course missing');
const lesson=(course.lessons||[]).find(l=>l.id==='sep-04');
assert(lesson,'sep-04 missing');
assert.equal(lesson.title,'Design docs, ADRs & practical UML');
const concepts=new Set((lesson.concepts||[]).map(x=>String(x).toLowerCase()));
for(const c of ['uml','class diagram','sequence diagram','component diagram','activity diagram','state diagram']) assert(concepts.has(c),`missing practical UML concept: ${c}`);
assert((lesson.objectives||[]).some(x=>/choose.*diagram/i.test(x)),'lesson must teach choosing diagrams from the engineering question');
assert(/Start from the question/i.test(lesson.explanation),'lesson explanation must stay question-first');
assert(/sequence diagram/i.test(lesson.explanation)&&/state diagram/i.test(lesson.explanation),'lesson explanation must distinguish practical diagram types');
assert(lesson.explanation.length<=380,'UML explanation should stay concise');
assert(/Checkout API/.test((lesson.examples||[])[0]||''),'native UML example must contain a checkout interaction');
assert(/Pending/.test((lesson.examples||[])[0]||'')&&/Paid/.test((lesson.examples||[])[0]||'')&&/Delivered/.test((lesson.examples||[])[0]||''),'native UML example must contain order lifecycle states');
const exercise=(course.exercises||[]).find(e=>e.id==='sep-ex-4');
assert(exercise&&/sequence diagrams/i.test(exercise.prompt)&&/state diagrams/i.test(exercise.prompt),'concise UML exercise missing');
assert(exercise.prompt.length<=130,'UML concept exercise should be brief');
const mirror=JSON.parse(fs.readFileSync(path.join(root,'assets','course-data','software-engineering-practice.json'),'utf8'));
assert.deepStrictEqual(mirror,course,'software-engineering course-data mirror drift');
const page=fs.readFileSync(path.join(root,'courses','software-engineering-practice.html'),'utf8');
for(const needle of ['Design docs, ADRs &amp; practical UML','Class diagram','Sequence diagram','Component diagram','Activity diagram','State diagram','Checkout API']) assert(page.includes(needle),`static Software Engineering page missing ${needle}`);
const guidance=fs.readFileSync(path.join(root,'assets','practice-guidance.js'),'utf8');
assert(guidance.includes('questionOnlyElement'),'concise UI should use the compact question-only guidance rather than the old multi-panel guidance');
const expanded=fs.readFileSync(path.join(root,'assets','assessment-expanded-descriptions.js'),'utf8');
assert(/prompts already state the task/.test(expanded),'duplicate assessment specification panels should be disabled');
console.log('AUD EECE 355 practical UML contract PASS — practical UML remains covered with concise explanations and prompts.');
