'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const start=read('START_CSAI.bat');
const install=read('INSTALL_ON_MY_COMPUTER.bat');
const server=read('local-server.js');
const launcher=read('desktop-launcher.js');
const bootstrap=read('server-bootstrap.js');
assert(fs.existsSync(path.join(root,'STOP_CSAI.bat')),'STOP_CSAI.bat missing');
assert(fs.existsSync(path.join(root,'server-bootstrap.js')),'server-bootstrap.js missing');
assert(start.includes('desktop-launcher.js'),'START_CSAI must use desktop-launcher.js');
assert(launcher.includes('/__health'),'desktop launcher must poll server health');
assert(launcher.includes('detached: true'),'desktop launcher must detach background server');
assert(launcher.includes("stdio: 'ignore'"),'desktop launcher must not pass inherited file handles to detached Windows server');
assert(launcher.includes("RELEASE = '5.74'"),'desktop launcher must identify the current release');
assert(launcher.includes('stopOldCsaiServerOnPort'),'desktop launcher must recover from stale local servers on port 5711');
assert(launcher.includes('120; i++'),'desktop launcher must allow up to 30 seconds for slow startup');
assert(launcher.includes('CSAI_NO_AUTO_OPEN'),'desktop launcher must suppress premature browser opening');
assert(launcher.includes('csai-server.log'),'desktop launcher must write a readable server log');
assert(bootstrap.includes('uncaughtException')&&bootstrap.includes('unhandledRejection'),'bootstrap must log fatal server failures');
assert(bootstrap.includes("require('./local-server.js')"),'bootstrap must load local-server.js');
assert(server.includes('release:RELEASE'),'health endpoint must identify release for stale-server replacement');
assert(launcher.includes('gh')&&launcher.includes('auth')&&launcher.includes('status'),'desktop launcher must check local GitHub CLI auth');
assert(!launcher.includes('TARGET_REPO'),'main launcher must not hard-code a repository target');
assert(server.includes("process.env.CSAI_NO_AUTO_OPEN!=='1'"),'local-server must honor background-launch mode');
assert(install.includes('desktop-launcher.js'),'installer must require desktop launcher');
assert(install.includes('server-bootstrap.js'),'installer must require server bootstrap');
assert(install.includes('gh auth status'),'installer must verify GitHub CLI authentication');
assert(!install.includes('gh repo view '),'main installer must not verify or choose a specific repository');
assert(install.includes('GitHub page'),'installer must direct the learner to the explicit GitHub page');
console.log('Reliable local launcher/GitHub verification contract: PASS');
